/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    Captcha: typeof import('./src/components/common/Captcha.vue')['default']
    ElBreadcrumb: typeof import('element-plus/es')['ElBreadcrumb']
    ElBreadcrumbItem: typeof import('element-plus/es')['ElBreadcrumbItem']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElIcon: typeof import('element-plus/es')['ElIcon']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElPageHeader: typeof import('element-plus/es')['ElPageHeader']
    ElTabPane: typeof import('element-plus/es')['ElTabPane']
    ElTabs: typeof import('element-plus/es')['ElTabs']
    Footer: typeof import('./src/components/layout/Footer.vue')['default']
    Frame: typeof import('./src/components/contact/Frame.vue')['default']
    Header: typeof import('./src/components/layout/Header.vue')['default']
    Index: typeof import('./src/components/profile/Index.vue')['default']
    Language: typeof import('./src/components/common/Language.vue')['default']
    Layout: typeof import('./src/components/layout/index.vue')['default']
    Main: typeof import('./src/components/profile/Main.vue')['default']
    Modal: typeof import('./src/components/contact/Modal.vue')['default']
    ProHeader: typeof import('./src/components/profile/ProHeader.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SelectMenu: typeof import('./src/components/common/SelectMenu.vue')['default']
    SliderCaptcha: typeof import('./src/components/common/SliderCaptcha.vue')['default']
    TheWelcome: typeof import('./src/components/TheWelcome.vue')['default']
    Uploader: typeof import('./src/components/common/Uploader.vue')['default']
    UserMenu: typeof import('./src/components/common/UserMenu.vue')['default']
  }
}
