/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    Captcha: typeof import('./components/common/Captcha.vue')['default']
    Footer: typeof import('./components/layout/Footer.vue')['default']
    Frame: typeof import('./components/contact/Frame.vue')['default']
    Header: typeof import('./components/layout/Header.vue')['default']
    Index: typeof import('./components/profile/Index.vue')['default']
    Language: typeof import('./components/common/Language.vue')['default']
    Layout: typeof import('./components/layout/index.vue')['default']
    Main: typeof import('./components/profile/Main.vue')['default']
    Modal: typeof import('./components/contact/Modal.vue')['default']
    ProHeader: typeof import('./components/profile/ProHeader.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SelectMenu: typeof import('./components/common/SelectMenu.vue')['default']
    SliderCaptcha: typeof import('./components/common/SliderCaptcha.vue')['default']
    TheWelcome: typeof import('./components/TheWelcome.vue')['default']
    Uploader: typeof import('./components/common/Uploader.vue')['default']
    UserMenu: typeof import('./components/common/UserMenu.vue')['default']
  }
}
